### ISSUE TITLE
python inference code?

### ISSUE THREAD

**Issue by zdyshine** [AIGAnimation/CAMDM#5]
Great work, can you provide python inference code?

**Comment by Shimingyi** [comment]
Hi @zdyshine , because our system requires an interactive environment for providing the runtime features such as HFTE, hence python is not a good choice for inference. But we have a the function to export bvh for a single prediction window within python, you can check: [evaluate_sampling]. This function will help for checking the network performance in the training stage.  (https://github.com/AIGAnimation/CAMDM/blob/main/PyTorch/network/training.py#L274).
